version: 2
updates:
  # Enable version updates for npm (root)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    reviewers:
      - 'Tonx-Cloud'
    assignees:
      - 'Tonx-Cloud'
    commit-message:
      prefix: 'chore(deps):'
      include: 'scope'

  # Enable version updates for npm (apps/api)
  - package-ecosystem: 'npm'
    directory: '/apps/api'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    reviewers:
      - 'Tonx-Cloud'
    assignees:
      - 'Tonx-Cloud'
    commit-message:
      prefix: 'chore(api):'
      include: 'scope'

  # Enable version updates for npm (apps/web)
  - package-ecosystem: 'npm'
    directory: '/apps/web'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    reviewers:
      - 'Tonx-Cloud'
    assignees:
      - 'Tonx-Cloud'
    commit-message:
      prefix: 'chore(web):'
      include: 'scope'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(ci):'
      include: 'scope'
