# Configuração do Alertmanager para My-WA-API
# Gerenciamento e roteamento de alertas

global:
  # Configurações SMTP para email
  smtp_smarthost: '${SMTP_HOST}:${SMTP_PORT}'
  smtp_from: '${EMAIL_FROM}'
  smtp_auth_username: '${SMTP_USER}'
  smtp_auth_password: '${SMTP_PASS}'
  
  # URLs base para templates
  slack_api_url: '${SLACK_WEBHOOK_URL}'

# Templates customizados
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Configuração de rotas
route:
  # Receptor padrão
  receiver: 'default'
  
  # Tempo para agrupar alertas
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 4h
  
  # Agrupamento de alertas
  group_by: ['alertname', 'severity', 'service']
  
  # Rotas específicas
  routes:
    # Alertas críticos - notificação imediata
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      group_interval: 1m
      repeat_interval: 30m
      routes:
        # API crítica - Slack + Email + SMS
        - match:
            service: api
          receiver: 'api-critical'
        # Banco crítico - DBA team
        - match:
            service: database
          receiver: 'database-critical'
    
    # Alertas de warning - notificação agrupada
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      group_interval: 10m
      repeat_interval: 2h
    
    # Alertas de infraestrutura
    - match:
        component: system
      receiver: 'infrastructure-alerts'
      group_interval: 15m
    
    # Alertas de WhatsApp
    - match:
        service: whatsapp
      receiver: 'whatsapp-alerts'
      group_interval: 5m

# Configurações de inibição
inhibit_rules:
  # Se API está down, não alertar sobre latência
  - source_match:
      alertname: 'APIDown'
    target_match:
      alertname: 'APIHighLatency'
    equal: ['service']
  
  # Se container está reiniciando, não alertar sobre saúde
  - source_match:
      alertname: 'ContainerRestarting'
    target_match_re:
      alertname: '.*Down'
    equal: ['instance']

# Configurações de receptores
receivers:
  # Receptor padrão (silencioso)
  - name: 'default'
    webhook_configs:
      - url: 'http://localhost:9093/api/v1/silence'
        send_resolved: true

  # Alertas críticos - múltiplos canais
  - name: 'critical-alerts'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-critical'
        title: '🚨 ALERTA CRÍTICO - My-WA-API'
        text: |
          *Alerta:* {{ .GroupLabels.alertname }}
          *Severidade:* {{ .GroupLabels.severity }}
          *Serviço:* {{ .GroupLabels.service }}
          *Descrição:* {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
          *Horário:* {{ range .Alerts }}{{ .StartsAt.Format "15:04:05 02/01/2006" }}{{ end }}
        send_resolved: true
        title_link: 'http://localhost:3030/d/my-wa-api'
    
    email_configs:
      - to: '${ALERT_EMAIL_CRITICAL}'
        subject: '🚨 ALERTA CRÍTICO - My-WA-API - {{ .GroupLabels.alertname }}'
        body: |
          Alerta crítico detectado no My-WA-API:
          
          Alerta: {{ .GroupLabels.alertname }}
          Severidade: {{ .GroupLabels.severity }}
          Serviço: {{ .GroupLabels.service }}
          
          Detalhes:
          {{ range .Alerts }}
          - {{ .Annotations.summary }}
          - {{ .Annotations.description }}
          - Início: {{ .StartsAt.Format "15:04:05 02/01/2006" }}
          {{ end }}
          
          Dashboard: http://localhost:3030/d/my-wa-api
          Alertmanager: http://localhost:9093
        send_resolved: true

  # Alertas específicos da API
  - name: 'api-critical'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#api-alerts'
        title: '🔥 API CRÍTICA - My-WA-API'
        text: |
          *API EM ESTADO CRÍTICO!*
          
          {{ range .Alerts }}
          *Problema:* {{ .Annotations.summary }}
          *Detalhes:* {{ .Annotations.description }}
          *Início:* {{ .StartsAt.Format "15:04:05 02/01/2006" }}
          {{ end }}
          
          <http://localhost:3030/d/api-dashboard|📊 Dashboard API>
          <http://localhost:9093|🚨 Alertmanager>
        send_resolved: true
        color: 'danger'
    
    webhook_configs:
      - url: '${DISCORD_WEBHOOK_URL}/slack'
        send_resolved: true

  # Alertas de banco de dados
  - name: 'database-critical'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#database-alerts'
        title: '💾 BANCO CRÍTICO - My-WA-API'
        text: |
          *PROBLEMA NO BANCO DE DADOS!*
          
          {{ range .Alerts }}
          *Problema:* {{ .Annotations.summary }}
          *Detalhes:* {{ .Annotations.description }}
          {{ end }}
        send_resolved: true
        color: 'danger'

  # Alertas de warning
  - name: 'warning-alerts'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts'
        title: '⚠️ Alerta - My-WA-API'
        text: |
          *Alerta de atenção:*
          
          {{ range .Alerts }}
          • {{ .Annotations.summary }}
          {{ end }}
        send_resolved: true
        color: 'warning'

  # Alertas de infraestrutura
  - name: 'infrastructure-alerts'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#infrastructure'
        title: '🖥️ Infraestrutura - My-WA-API'
        text: |
          *Alerta de infraestrutura:*
          
          {{ range .Alerts }}
          • {{ .Annotations.summary }}: {{ .Annotations.description }}
          {{ end }}
        send_resolved: true

  # Alertas do WhatsApp
  - name: 'whatsapp-alerts'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#whatsapp'
        title: '💬 WhatsApp - My-WA-API'
        text: |
          *Alerta do WhatsApp:*
          
          {{ range .Alerts }}
          • {{ .Annotations.summary }}
          {{ end }}
        send_resolved: true
        color: 'good'
